### ISSUE TITLE
arduino mega - glediator and ws2812

### ISSUE THREAD

**Issue by karlTH** [olliesmit/Glediator-WS2811-Parallel#1]
hello
happy new year

i have arduino mega and ws2812 how do i drive my strip with glediator ?

tanks

**Comment by olliesmit** [comment]
If it is just one strip/strips in series, look at the official website. if not upload my sketch to the arduino. and use the pins listed in my sketch. it may need some configuring. also glediator needs to be set to glediator in the output options and the com port det to 1000000 baud
